import { Toaster } from "react-hot-toast";
import HeroProvider from "./components/HeroProvider";
import StoreProvider from "./components/StoreProvider";
import "./globals.css";
import MainNavbar from "./components/MainNavbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <StoreProvider>
          <HeroProvider>
            <MainNavbar/>
            {children}
            </HeroProvider>
        </StoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
